telovendo/home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.bienvenida, name='bienvenida'),
    path('mostrarUsuario', views.mostrarUsuario, name='mostrarUsuario')
]

telovendo/telovendo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

telovendo/home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Usuario(AbstractUser):


  username = models.CharField(max_length=50, null=False, unique=True)
  nombre = models.CharField(max_length=50,  null=True)
  apellido = models.CharField(max_length=50,  null=True)
  rut = models.CharField(max_length=50,  null=True)
  email = models.EmailField(max_length=254,  null=True,  unique=True)
  telefono = models.CharField(max_length=15)
  fecha_registro = models.DateTimeField(auto_now=False, auto_now_add=True)
  password = models.CharField(max_length=128, null=True)
  
  def save(self, *args, **kwargs):
    self.username = self.email  # Asignamos el valor del email al username
    super().save(*args, **kwargs)

# Create your models here.



    #OJO Agregar los modelos al admin !!!

telovendo/home/views.py
from django.shortcuts import render
from .models import Usuario



# Create your views here.

def bienvenida(request):
    return render(request, 'home/index.html', {
        } )

def mostrarUsuario(request):
    lista_usuario = Usuario.objects.all()
    return render(request, 'home/mostrar_usuario.html', {
        'lista_usuario' : lista_usuario
    })

telovendo/home/templates/home/index.html
{% extends 'home/layout/base.html' %}
{% block main %}
    <body>
        <div class="container mt-5">
        <div class="row">
            <div class="col-sm-4">
            <h2>Te lo vendo</h2>
            <h5>Moda en un clic, estilo en tu puerta.</h5>
            <p>Te lo vendo nació de la pasión de Isabella por la moda y la conveniencia de las compras en línea. Con un enfoque en la asesoría personalizada, creó una tienda de ropa en línea única y exitosa, que se expandió internacionalmente y se convirtió en una referencia en el mundo de la moda en línea.</p>
            <h3 class="mt-4">Nuestras Secciones</h3>
            <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                <a class="nav-link active" href="#">Deportes</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">Formal</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">Casual</a>
                </li>
                <li class="nav-item">
                <a class="nav-link disabled" href="#">Otros</a>
                </li>
            </ul>
            <hr class="d-sm-none">
            </div>
            <div class="col-sm-8">
            <h2>¡Una experiencia increíble en "Te lo vendo"!</h2>
            <h5>Title description, Dic 7, 2022</h5>
            <p>¡Wow, simplemente wow! Mi primera compra en "Te lo vendo" fue una experiencia fantástica. La asesoría de moda en línea fue acertada, y estoy enamorada de cada prenda que compré. ¡Es como si hubieran leído mi mente y me presentaran exactamente lo que estaba buscando!</p>
            <p>#TeLoVendo #ExperienciaDeCompra #ModaEnLínea #EstiloÚnico #ClienteFeliz</p>
            <h2 class="mt-5"> ¡Amor a primera compra en "Te lo vendo"!</h2>
            <h5>Title description, May 2, 2023</h5>
            <p>¡Estoy encantado con mi compra en "Te lo vendo"! La asesoría de moda en línea fue excepcional, me ayudaron a encontrar exactamente lo que buscaba y descubrí algunas prendas que se adaptaban perfectamente a mi estilo. ¡El equipo de servicio al cliente fue amable y atento en todo momento!</p>
            <p>#TeLoVendo #ExperienciaDeCompra #AmorALaPrimeraCompra #ModaEnLínea #ClienteFeliz</p>
            </div>
        </div>
        </div>
        
        <div class="mt-5 p-4 bg-dark text-white text-center">
        <p>Footer</p>
        </div>
        
        
        
        </body>
{% endblock main %}

telovendo/home/templates/home/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Te lo vendo</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href=" {% url 'home:bienvenida' %} ">Te lo Vendo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link" href=" {% url 'home:mostrarUsuario' %} ">Mostrar Usuarios</a>
                </li>
            </ul>
            </div>
        </nav>
    </header>
    <main>
        {% block main %}
        {% endblock main %}
    </main>
    <footer>
        
    </footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

telovendo/home/templates/home/mostrar_usuario.html
{% extends 'home/layout/base.html' %}
{% block main %}
<h2>Mostrando usuarios</h2>
{% for user in lista_usuario %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Apellido</th>
            <th scope="col">Rut</th>
            <th scope="col">email</th>
            <th scope="col">Fecha de Registro</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ user.nombre }}</td>
            <td>{{ user.apellido }}</td>
            <td>{{ user.rut }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.fecha_registro }}</td>
        </tr>
        </tbody>
    </table>
{% endfor %}
{% endblock main %} 